import { defineRule } from './define-rule.ts';

interface AgentAttributionOptions {
  allow?: string[];
  patterns?: string[];
}

interface AgentEntry {
  label: string;
  patterns: RegExp[];
}

const KNOWN_AGENTS: ReadonlyMap<string, AgentEntry> = new Map([
  ['claude', {
    label: 'Claude Code',
    patterns: [
      /^co-authored-by:\s.*\bclaude\b/im,
      /^co-authored-by:\s.*noreply@anthropic\.com/im,
      /generated with .*claude code/i,
    ],
  }],
  ['copilot', {
    label: 'GitHub Copilot',
    patterns: [
      /^co-authored-by:\s.*\bcopilot\b/im,
      /^co-authored-by:\s.*copilot@github\.com/im,
    ],
  }],
  ['cursor', {
    label: 'Cursor',
    patterns: [
      /^co-authored-by:\s.*\bcursor\b/im,
      /^co-authored-by:\s.*cursoragent@cursor\.com/im,
    ],
  }],
  ['gemini', {
    label: 'Gemini',
    patterns: [
      /^co-authored-by:\s.*\bgemini\b/im,
    ],
  }],
  ['codex', {
    label: 'Codex',
    patterns: [
      /^co-authored-by:\s.*\bcodex\b/im,
      /^co-authored-by:\s.*noreply@openai\.com/im,
    ],
  }],
  ['vibe', {
    label: 'Mistral Vibe',
    patterns: [
      /^co-authored-by:\s.*\bvibe\b/im,
      /^co-authored-by:\s.*vibe@mistral\.ai/im,
      /generated by mistral vibe/i,
    ],
  }],
  ['aider', {
    label: 'Aider',
    patterns: [
      /^co-authored-by:\s.*\baider\b/im,
      /^co-authored-by:\s.*noreply@aider\.chat/im,
    ],
  }],
  ['opencode', {
    label: 'OpenCode',
    patterns: [
      /^co-authored-by:\s.*\bopencode\b/im,
      /^co-authored-by:\s.*noreply@opencode\.ai/im,
      /generated with opencode/i,
    ],
  }],
  ['windsurf', {
    label: 'Windsurf',
    patterns: [
      /^co-authored-by:\s.*\bwindsurf\b/im,
      /^co-authored-by:\s.*\bcascade\b/im,
      /^co-authored-by:\s.*cascade@windsurf\.com/im,
    ],
  }],
]);

export const KNOWN_AGENT_IDS: ReadonlySet<string> = new Set(KNOWN_AGENTS.keys());

export const agentAttributionRule = defineRule<AgentAttributionOptions>({
  meta: {
    name: 'agent-attribution',
    description: 'Block or warn on AI-agent commit attribution markers',
    category: 'content',
    requiresGit: false,
    defaultSeverity: 'error',
  },
  validate({ commit, options }) {
    const problems: { message: string; suggestion?: string }[] = [];
    const allowSet = new Set(options.allow ?? []);

    const unknownIds = [...allowSet].filter((id) => !KNOWN_AGENTS.has(id));
    if (unknownIds.length > 0) {
      const label = unknownIds.length === 1 ? 'Unknown agent ID' : 'Unknown agent IDs';
      const quoted = unknownIds.map((id) => `"${id}"`).join(', ');
      problems.push({
        message: `${label} ${quoted} in allow list. Known agents: ${[...KNOWN_AGENTS.keys()].join(', ')}.`,
        suggestion: 'Check the agent-attribution allow option in your config.',
      });
      return problems;
    }

    for (const [id, agent] of KNOWN_AGENTS) {
      if (allowSet.has(id)) continue;
      for (const pattern of agent.patterns) {
        if (pattern.test(commit.raw)) {
          problems.push({
            message: `Commit contains ${agent.label} attribution marker.`,
            suggestion: `Remove the ${agent.label} attribution or add "${id}" to the allow list.`,
          });
          break;
        }
      }
    }

    for (const patternStr of options.patterns ?? []) {
      let re: RegExp;
      try {
        // nosemgrep: javascript.lang.security.audit.detect-non-literal-regexp.detect-non-literal-regexp
        re = new RegExp(patternStr, 'im');
      } catch {
        problems.push({
          message: `Invalid agent-attribution pattern: "${patternStr}".`,
          suggestion: 'Check the regex syntax in your config.',
        });
        continue;
      }

      if (re.test(commit.raw)) {
        problems.push({
          message: `Commit matches custom agent-attribution pattern /${patternStr}/.`,
          suggestion: 'Remove the matching attribution marker.',
        });
      }
    }

    return problems;
  },
});
