import { strict as assert } from 'node:assert';
import { describe, it } from 'node:test';
import { parseCommit } from '../../../src/parser.ts';
import { agentAttributionRule, KNOWN_AGENT_IDS } from '../../../src/rules/agent-attribution.ts';
import { attribution } from '../../fixtures/messages.ts';

function run(message: string, options: { allow?: string[]; patterns?: string[] } = {}) {
  return agentAttributionRule.validate({
    commit: parseCommit(message),
    git: null,
    options,
  });
}

describe('agent-attribution', () => {
  it('passes a clean commit with no markers', () => {
    const problems = run('feat: add login');
    assert.equal(problems.length, 0);
  });

  it('detects Claude Co-Authored-By in footer position', () => {
    const problems = run(attribution.claudeFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Claude Code/);
  });

  it('detects Claude Co-Authored-By in body position', () => {
    const problems = run(attribution.claudeInBody);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Claude Code/);
  });

  it('detects Generated with [Claude Code] boilerplate', () => {
    const problems = run(attribution.claudeGenerated);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Claude Code/);
  });

  it('detects bracket-less Claude Code boilerplate', () => {
    const msg = 'feat: add login\n\nGenerated with Claude Code';
    const problems = run(msg);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Claude Code/);
  });

  it('detects Copilot Co-Authored-By', () => {
    const problems = run(attribution.copilotFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /GitHub Copilot/);
  });

  it('detects Cursor Co-Authored-By', () => {
    const problems = run(attribution.cursorFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Cursor/);
  });

  it('detects Codex Co-Authored-By', () => {
    const problems = run(attribution.codexFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Codex/);
  });

  it('detects Gemini Co-Authored-By', () => {
    const problems = run(attribution.geminiFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Gemini/);
  });

  it('detects Mistral Vibe Co-Authored-By', () => {
    const problems = run(attribution.vibeFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Mistral Vibe/);
  });

  it('detects Generated by Mistral Vibe boilerplate', () => {
    const problems = run(attribution.vibeGenerated);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Mistral Vibe/);
  });

  it('detects bare Vibe co-author name (fail-closed)', () => {
    const msg = 'feat: add login\n\nCo-authored-by: Vibe <dev@company.com>';
    const problems = run(msg);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Mistral Vibe/);
  });

  it('detects Aider Co-Authored-By', () => {
    const problems = run(attribution.aiderFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Aider/);
  });

  it('detects OpenCode Co-Authored-By', () => {
    const problems = run(attribution.opencodeFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /OpenCode/);
  });

  it('detects Generated with opencode boilerplate', () => {
    const problems = run(attribution.opencodeGenerated);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /OpenCode/);
  });

  it('detects Windsurf/Cascade Co-Authored-By', () => {
    const problems = run(attribution.windsurfFooter);
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Windsurf/);
  });

  describe('email-only detection', () => {
    it('detects copilot@github.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: AI Bot <copilot@github.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /GitHub Copilot/);
    });

    it('detects cursoragent@cursor.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <cursoragent@cursor.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Cursor/);
    });

    it('detects gemini@google.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <gemini@google.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Gemini/);
    });

    it('detects noreply@openai.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: AI <noreply@openai.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Codex/);
    });

    it('detects noreply@anthropic.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: AI <noreply@anthropic.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Claude Code/);
    });

    it('detects vibe@mistral.ai even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <vibe@mistral.ai>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Mistral Vibe/);
    });

    it('detects noreply@aider.chat even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <noreply@aider.chat>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Aider/);
    });

    it('detects noreply@opencode.ai even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <noreply@opencode.ai>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /OpenCode/);
    });

    it('detects cascade@windsurf.com even with a different name', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Bot <cascade@windsurf.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Windsurf/);
    });
  });

  describe('false-positive prevention', () => {
    it('does not false-positive on agent name in subject', () => {
      const problems = run('docs: add claude-code integration guide');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on agent name in body text', () => {
      const problems = run('docs: update\n\nThis adds documentation for the Claude Code integration.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on copilot in subject', () => {
      const problems = run('feat: add copilot support');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on copilot in body', () => {
      const problems = run('docs: update\n\nDescribes the Copilot integration flow.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on cursor in subject', () => {
      const problems = run('fix: restore cursor position after undo');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on cursor in body', () => {
      const problems = run('fix: blink\n\nThe cursor was invisible in dark mode.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on codex in subject', () => {
      const problems = run('docs: add codex migration notes');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on codex in body', () => {
      const problems = run('docs: update\n\nMigrate from Codex to newer model.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on gemini in subject', () => {
      const problems = run('feat: integrate gemini search');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on gemini in body', () => {
      const problems = run('docs: update\n\nIntegrate with Google Gemini API.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on vibe in subject', () => {
      const problems = run('feat: add vibe check endpoint');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on vibe in body', () => {
      const problems = run('docs: update\n\nThis captures the vibe of the product.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on aider in subject', () => {
      const problems = run('docs: add aider setup instructions');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on aider in body', () => {
      const problems = run('docs: update\n\nInstall aider for pair programming.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on opencode in subject', () => {
      const problems = run('feat: add opencode compatibility');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on opencode in body', () => {
      const problems = run('docs: update\n\nCompare with OpenCode workflow.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on windsurf in subject', () => {
      const problems = run('feat: add windsurf tracking');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on windsurf in body', () => {
      const problems = run('docs: update\n\nMigrated from Windsurf editor.');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on cascade in subject', () => {
      const problems = run('fix: handle cascade delete in database');
      assert.equal(problems.length, 0);
    });

    it('does not false-positive on cascade in body', () => {
      const problems = run('fix: cleanup\n\nThe cascade operation was failing silently.');
      assert.equal(problems.length, 0);
    });

    it('matches a human Co-authored-by with an agent-like name (fail-closed)', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Claude Dupont <claude.dupont@company.com>';
      const problems = run(msg);
      assert.equal(problems.length, 1);
    });
  });

  describe('allow option', () => {
    it('exempts allowed agent', () => {
      const problems = run(attribution.claudeFooter, { allow: ['claude'] });
      assert.equal(problems.length, 0);
    });

    it('exempts copilot when allowed', () => {
      const problems = run(attribution.copilotFooter, { allow: ['copilot'] });
      assert.equal(problems.length, 0);
    });

    it('exempts cursor when allowed', () => {
      const problems = run(attribution.cursorFooter, { allow: ['cursor'] });
      assert.equal(problems.length, 0);
    });

    it('exempts codex when allowed', () => {
      const problems = run(attribution.codexFooter, { allow: ['codex'] });
      assert.equal(problems.length, 0);
    });

    it('exempts gemini when allowed', () => {
      const problems = run(attribution.geminiFooter, { allow: ['gemini'] });
      assert.equal(problems.length, 0);
    });

    it('exempts vibe when allowed', () => {
      const problems = run(attribution.vibeFooter, { allow: ['vibe'] });
      assert.equal(problems.length, 0);
    });

    it('exempts aider when allowed', () => {
      const problems = run(attribution.aiderFooter, { allow: ['aider'] });
      assert.equal(problems.length, 0);
    });

    it('exempts opencode when allowed', () => {
      const problems = run(attribution.opencodeFooter, { allow: ['opencode'] });
      assert.equal(problems.length, 0);
    });

    it('exempts windsurf when allowed', () => {
      const problems = run(attribution.windsurfFooter, { allow: ['windsurf'] });
      assert.equal(problems.length, 0);
    });

    it('exempts multiple allowed agents', () => {
      const problems = run(attribution.mixedClaudeCopilot, { allow: ['claude', 'copilot'] });
      assert.equal(problems.length, 0);
    });

    it('errors on non-allowed agent in mixed attribution', () => {
      const problems = run(attribution.mixedClaudeCopilot, { allow: ['claude'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /GitHub Copilot/);
    });

    it('blocks all agents when allow is empty', () => {
      const problems = run(attribution.mixedClaudeCopilot, { allow: [] });
      assert.equal(problems.length, 2);
    });

    it('fails loud on unknown agent ID', () => {
      const problems = run('feat: add login', { allow: ['unknown-agent'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Unknown agent ID "unknown-agent"/);
    });

    it('fails loud on unknown agent ID before checking markers', () => {
      const problems = run(attribution.claudeFooter, { allow: ['bad-id'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Unknown agent ID/);
    });

    it('lists known agent IDs in the error message', () => {
      const problems = run('feat: add login', { allow: ['nope'] });
      assert.match(problems[0]!.message, /claude/);
      assert.match(problems[0]!.message, /copilot/);
      assert.match(problems[0]!.message, /vibe/);
    });

    it('reports all unknown agent IDs at once', () => {
      const problems = run('feat: add login', { allow: ['bad1', 'bad2'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Unknown agent IDs/);
      assert.match(problems[0]!.message, /"bad1"/);
      assert.match(problems[0]!.message, /"bad2"/);
    });
  });

  describe('patterns option', () => {
    it('matches extra deny pattern', () => {
      const msg = 'feat: add login\n\nBuilt-with: some-internal-tool';
      const problems = run(msg, { patterns: ['built-with:\\s*some-internal-tool'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /custom agent-attribution pattern/);
    });

    it('does not match when pattern is absent in commit', () => {
      const problems = run('feat: add login', { patterns: ['built-with:\\s*some-tool'] });
      assert.equal(problems.length, 0);
    });

    it('reports invalid regex gracefully', () => {
      const problems = run('feat: add login', { patterns: ['[invalid'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /Invalid agent-attribution pattern/);
    });

    it('custom patterns still fire when known agents are allowed', () => {
      const msg = 'feat: add login\n\nMade-with: internal-ai-tool';
      const problems = run(msg, { allow: ['claude', 'copilot'], patterns: ['made-with:\\s*internal-ai-tool'] });
      assert.equal(problems.length, 1);
      assert.match(problems[0]!.message, /custom agent-attribution pattern/);
    });
  });

  describe('known agents taxonomy', () => {
    it('includes all expected agent IDs', () => {
      for (const id of ['claude', 'copilot', 'cursor', 'gemini', 'codex', 'vibe', 'aider', 'opencode', 'windsurf']) {
        assert.ok(KNOWN_AGENT_IDS.has(id), `missing agent ID: ${id}`);
      }
    });

    it('does not include @users.noreply.github.com as copilot marker', () => {
      const msg = 'feat: add login\n\nCo-authored-by: Jane <12345+jane@users.noreply.github.com>';
      const problems = run(msg);
      assert.equal(problems.length, 0);
    });
  });

  it('detects case-insensitive Co-Authored-By variations', () => {
    const problems = run('feat: add\n\nco-authored-by: Claude <noreply@anthropic.com>');
    assert.equal(problems.length, 1);
    assert.match(problems[0]!.message, /Claude Code/);
  });

  it('includes actionable suggestion with agent ID', () => {
    const problems = run(attribution.vibeFooter);
    assert.equal(problems.length, 1);
    assert.ok(problems[0]!.suggestion);
    assert.match(problems[0]!.suggestion!, /vibe/);
    assert.match(problems[0]!.suggestion!, /allow/);
  });

  it('reports one problem per agent maximum', () => {
    const msg =
      'feat: add login\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n\n🤖 Generated with [Claude Code](https://claude.ai/code)';
    const problems = run(msg);
    const claudeProblems = problems.filter((p) => p.message.includes('Claude Code'));
    assert.equal(claudeProblems.length, 1);
  });
});
