export {
  parseCommit,
  defineConfig,
  defineRule,
  loadConfig,
  getPreset,
  listCommitsInRange,
  readCommitMessage,
  readGitMetaOrNull,
  readCommitsInRange,
  validate,
  validateRangeRules,
  builtinRules,
  getRule,
  humanFormatter,
  jsonFormatter,
  sarifFormatter,
} from './src/index.ts';

export type {
  ParsedCommit,
  Footer,
  GitMeta,
  CommitRecord,
  Rule,
  RuleMeta,
  RuleContext,
  RangeRuleContext,
  RangeCommit,
  RuleProblem,
  RuleConfig,
  RuleCategory,
  Severity,
  ActiveSeverity,
  UserConfig,
  Preset,
  ResolvedConfig,
  ResolvedRuleEntry,
  ValidationReport,
  RuleResult,
  Formatter,
  FormatOptions,
} from './src/types.ts';
