/** Valid commit messages by variant. */
export const valid = {
  simple: 'feat: add login',
  withScope: 'fix(api): handle timeout',
  chore: 'chore: update tooling',
  withBody: 'feat: add login\n\nThis implements the user login feature.',
  withFooter: 'feat: add login\n\nBody text.\n\nReviewed-by: Alice',
  withBreakingMarker: 'feat!: drop legacy API',
  withBreakingFooter: 'feat: change\n\nBREAKING CHANGE: removed /v1 endpoint',
  withScopeAndBreaking: 'refactor(core)!: rewrite internals',
  withMultipleFooters: 'fix: bug\n\nBody.\n\nReviewed-by: Alice\nRefs #123',
} as const;

/** Invalid commit messages by failure mode. */
export const invalid = {
  noColon: 'fix bug',
  empty: '',
  whitespaceOnly: '   ',
  missingSubject: 'feat: ',
  unsupportedType: 'docs: update readme',
} as const;

/** Commit messages with AI-agent attribution markers. */
export const attribution = {
  claudeFooter: 'feat: add login\n\nBody text.\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
  claudeGenerated: 'feat: add login\n\n🤖 Generated with [Claude Code](https://claude.ai/code)',
  copilotFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: Copilot <copilot@github.com>',
  cursorFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: Cursor <cursoragent@cursor.com>',
  codexFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: Codex <noreply@openai.com>',
  vibeFooter: 'feat: add login\n\nBody text.\n\nCo-Authored-By: Mistral Vibe <vibe@mistral.ai>',
  vibeGenerated: 'feat: add login\n\nGenerated by Mistral Vibe.\n\nCo-Authored-By: Mistral Vibe <vibe@mistral.ai>',
  geminiFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: Gemini <gemini@google.com>',
  aiderFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: aider (gpt-4) <noreply@aider.chat>',
  opencodeFooter: 'feat: add login\n\nBody text.\n\nCo-Authored-By: opencode <noreply@opencode.ai>',
  opencodeGenerated: 'feat: add login\n\n🤖 Generated with opencode\n\nCo-Authored-By: opencode <noreply@opencode.ai>',
  windsurfFooter: 'feat: add login\n\nBody text.\n\nCo-authored-by: Cascade Agent <cascade@windsurf.com>',
  mixedClaudeCopilot: 'feat: add login\n\nBody text.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-authored-by: Copilot <copilot@github.com>',
  claudeInBody: 'feat: add login\n\nFirst paragraph.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n\nAnother paragraph.',
} as const;

/** Edge-case commit messages. */
export const edge = {
  longSubject: `feat: ${'a'.repeat(200)}`,
  uppercaseSubject: 'feat: Add Login',
  multilineBody: 'feat: add\n\nLine 1.\n\nLine 2.\n\nLine 3.',
  longBodyLine: `feat: add\n\n${'a'.repeat(150)}`,
  breakingDashFooter: 'feat: change\n\nBREAKING-CHANGE: new behavior',
  footerContinuation: 'fix: bug\n\nBREAKING CHANGE: first line\ncontinuation line',
  nonAlphaSubjectStart: 'feat: 123 numbers first',
} as const;
